In [1]:
import numpy as np

In [2]:
np.random.rand(4, 4)

array([[0.37605944, 0.15495608, 0.5850792 , 0.46629767],
       [0.63639203, 0.48229795, 0.03536173, 0.2646435 ],
       [0.91811679, 0.78388389, 0.33439383, 0.98740256],
       [0.41795917, 0.34267801, 0.89677047, 0.00798119]])

In [3]:
np.random.randn(4,4)

array([[-0.69262951, -0.28632616, -0.09441807, -1.87871685],
       [ 1.37624568,  0.13103518, -0.86878219, -0.15392984],
       [-0.19585023,  1.3764389 ,  0.4803041 , -0.8053271 ],
       [ 0.80127057, -0.29967777,  0.62620226, -1.62500331]])

In [5]:
np.random.randint(1,30, 2)

array([ 6, 21])

In [11]:
np.random.seed(40)

In [12]:
np.random.randint(1,40)

7

In [43]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr.shape

(25,)

In [16]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [18]:
renarr = np.random.randint(1,50,10)
renarr

array([28, 10, 33, 10,  9, 31, 16, 15, 29, 41])

In [19]:
renarr.max()

41

In [20]:
renarr.min()

9

In [21]:
renarr.argmax()

9

In [22]:
renarr.argmin()

4

In [29]:
renarr.dtype

dtype('int32')

In [23]:
import sys
py_arr = [3, 1, 5]
py_arr

[3, 1, 5]

In [30]:
sys.getsizeof(1)*len(py_arr)

84

In [31]:
np_arr = np.array(py_arr)
np_arr

array([3, 1, 5])

In [27]:
np_arr.itemsize * np_arr.size

12

In [36]:
print(arr.reshape(5,5))
arr.reshape(5,5).sum(axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([50, 55, 60, 65, 70])

In [37]:
arr.reshape(5,5).sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [45]:
arr.reshape(5,5).T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [44]:
np.where(arr>5)

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24], dtype=int64),)